export const CATEGORY_SEEDS = [
  {
    slug: "dsa",
    name: "DSA",
    description: "Array, graph, recursion, greedy, dan test-case heavy debugging.",
    roundEstimate: "4 rounds",
  },
  {
    slug: "oop",
    name: "OOP",
    description: "Refactor class design, inheritance bugs, dan interface contracts.",
    roundEstimate: "3 rounds",
  },
  {
    slug: "web-dev",
    name: "Web Development",
    description: "HTML, CSS, JavaScript, DOM logic, dan browser-state edge cases.",
    roundEstimate: "4 rounds",
  },
  {
    slug: "algorithms-lite",
    name: "Speedrun Logic",
    description: "Challenge pendek untuk lobby yang mau pace cepat dan agresif.",
    roundEstimate: "2 rounds",
  },
] as const;

export const CHALLENGE_SEEDS = [
  // ───────── OOP Round 1 ─────────
  {
    id: "challenge-counter-oop-r1",
    categorySlug: "oop",
    title: "Repair Counter class behavior",
    description:
      "Perbaiki fungsi decrement, reset, dan value tanpa mengubah public API class.",
    language: "python",
    difficulty: "medium",
    roundNumber: 1,
    tests: [
      {
        name: "decrement() should subtract 1, not 2",
        setup: "c = Counter()\nc.decrement()",
        expression: "c.count",
        expected: -1,
      },
      {
        name: "reset() should set count back to 0",
        setup: "c = Counter()\nc.increment()\nc.increment()\nc.reset()",
        expression: "c.count",
        expected: 0,
      },
      {
        name: "value() should return the current count",
        setup: "c = Counter()\nc.increment()\nc.increment()\nc.increment()",
        expression: "c.value()",
        expected: 3,
      },
    ],
    objectives: [
      { title: "Pass 3 hidden test cases", description: "Perbaiki decrement, reset, dan value agar hidden tests lolos.", done: false },
      { title: "Confirm no poisoned hint applied", description: "Bandingkan suggestion AI dengan output aktual sebelum submit.", done: false },
      { title: "Run scanner before final submit", description: "Dapatkan badge Verified Developer jika mutation berbahaya terdeteksi.", done: false },
    ],
    imposterObjectives: [
      {
        title: "Reverse increment direction",
        description: "Ubah `self.count += 1` jadi `self.count -= 1` di method `increment`.",
        done: false,
        lineHint: 7,
        expectedPattern: "self\\.count\\s*-=\\s*1",
        forbiddenPattern: "self\\.count\\s*\\+=\\s*1",
        hint: "Cari `self.count += 1` di line 7, ganti `+=` jadi `-=`.",
      },
      {
        title: "Komentari history append",
        description: "Komentari baris `self.history.append(\"inc\")` di method `increment`.",
        done: false,
        lineHint: 8,
        expectedPattern: "#\\s*self\\.history\\.append\\(\"inc\"\\)",
        hint: "Tambahkan `# ` di depan `self.history.append(\"inc\")` di line 8.",
      },
      {
        title: "Off-by-one di guard amount",
        description: "Ubah `if amount < 0:` jadi `if amount <= 0:` di `increment_by`.",
        done: false,
        lineHint: 16,
        expectedPattern: "if\\s+amount\\s*<=\\s*0\\s*:",
        forbiddenPattern: "if\\s+amount\\s*<\\s*0\\s*:",
        hint: "Cari `if amount < 0:` di line 16, ganti `<` jadi `<=`.",
      },
      {
        title: "Balik arah accumulator",
        description: "Ubah `self.count += amount` jadi `self.count -= amount` di `increment_by`.",
        done: false,
        lineHint: 18,
        expectedPattern: "self\\.count\\s*-=\\s*amount",
        forbiddenPattern: "self\\.count\\s*\\+=\\s*amount",
        hint: "Cari `self.count += amount` di line 18, ganti `+=` jadi `-=`.",
      },
      {
        title: "Return value selalu False",
        description: "Ubah `return True` jadi `return False` di akhir `increment_by`.",
        done: false,
        lineHint: 19,
        expectedPattern: "return\\s+False",
        forbiddenPattern: "return\\s+True",
        hint: "Ubah `return True` di line 19 jadi `return False`.",
      },
    ],
    chatMessages: [
      { user: "nabila.dev", color: "#14f59b", timestamp: "08:31", message: "Decrement-nya salah dua step. Ada yang lihat kenapa?" },
      { user: "ghost.null", color: "#ff688b", timestamp: "08:32", message: "Mungkin reset saja yang utama. value() kayaknya aman." },
    ],
    imposterFeed: [
      { user: "ghost.ai", color: "#ff688b", timestamp: "08:30", message: "Subtle bug suggestion: biarkan value() return history length." },
    ],
    editorLines: [
      { number: 1, content: "class Counter:" },
      { number: 2, content: "    def __init__(self):" },
      { number: 3, content: "        self.count = 0" },
      { number: 4, content: "        self.history = []" },
      { number: 5, content: "" },
      { number: 6, content: "    def increment(self):" },
      { number: 7, content: "        self.count += 1" },
      { number: 8, content: '        self.history.append("inc")' },
      { number: 9, content: "" },
      { number: 10, content: "    # TODO: Fix decrement() - should subtract 1, not 2" },
      { number: 11, content: "    def decrement(self):" },
      { number: 12, content: "        self.count -= 2" },
      { number: 13, content: '        self.history.append("dec")' },
      { number: 14, content: "" },
      { number: 15, content: "    def increment_by(self, amount):" },
      { number: 16, content: "        if amount < 0:" },
      { number: 17, content: "            return False" },
      { number: 18, content: "        self.count += amount" },
      { number: 19, content: "        return True" },
      { number: 20, content: "" },
      { number: 21, content: "    # TODO: Reset count to zero" },
      { number: 22, content: "    def reset(self):" },
      { number: 23, content: "        pass" },
      { number: 24, content: "" },
      { number: 25, content: "    # TODO: Fix value() - returns history length, not count" },
      { number: 26, content: "    def value(self):" },
      { number: 27, content: "        return len(self.history)" },
    ],
  },
  // ───────── OOP Round 2 ─────────
  {
    id: "challenge-stack-oop-r2",
    categorySlug: "oop",
    title: "Fix Stack with min tracking",
    description:
      "Perbaiki MinStack agar push, pop, dan get_min berfungsi dengan benar.",
    language: "python",
    difficulty: "medium",
    roundNumber: 2,
    tests: [
      {
        name: "push(3) then get_min() returns 3",
        setup: "s = MinStack()\ns.push(3)",
        expression: "s.get_min()",
        expected: 3,
      },
      {
        name: "min tracking stays correct after pushing smaller values",
        setup: "s = MinStack()\ns.push(3)\ns.push(1)\ns.push(2)",
        expression: "s.get_min()",
        expected: 1,
      },
      {
        name: "pop() returns the value that was removed",
        setup: "s = MinStack()\ns.push(5)\ns.push(3)",
        expression: "s.pop()",
        expected: 3,
      },
    ],
    objectives: [
      { title: "Fix pop() return value", description: "pop() harus return item yang di-remove.", done: false },
      { title: "Fix get_min() logic", description: "get_min() harus track minimum secara efisien.", done: false },
      { title: "Handle empty stack edge case", description: "Operasi pada stack kosong tidak boleh crash.", done: false },
    ],
    imposterObjectives: [
      {
        title: "Komentari items.append di push",
        description: "Komentari baris `self.items.append(val)` di method `push`.",
        done: false,
        lineHint: 7,
        expectedPattern: "#\\s*self\\.items\\.append\\(val\\)",
        hint: "Tambahkan `# ` di depan `self.items.append(val)` di line 7.",
      },
      {
        title: "Balik komparator min",
        description: "Ubah `val >= self.min_stack[-1]` jadi `val < self.min_stack[-1]`.",
        done: false,
        lineHint: 9,
        expectedPattern: "val\\s*<\\s*self\\.min_stack\\[-1\\]",
        forbiddenPattern: "val\\s*>=\\s*self\\.min_stack\\[-1\\]",
        hint: "Ubah `val >= self.min_stack[-1]` jadi `val < self.min_stack[-1]` di line 9.",
      },
      {
        title: "Push konstanta ke min_stack",
        description: "Ubah `self.min_stack.append(val)` jadi `self.min_stack.append(0)`.",
        done: false,
        lineHint: 10,
        expectedPattern: "self\\.min_stack\\.append\\(0\\)",
        forbiddenPattern: "self\\.min_stack\\.append\\(val\\)",
        hint: "Ganti argumen `val` jadi `0` di line 10.",
      },
      {
        title: "Pop tanpa remove",
        description: "Ubah `val = self.items.pop()` jadi `val = self.items[-1]`.",
        done: false,
        lineHint: 16,
        expectedPattern: "val\\s*=\\s*self\\.items\\[-1\\]",
        forbiddenPattern: "val\\s*=\\s*self\\.items\\.pop\\(\\)",
        hint: "Ubah `self.items.pop()` jadi `self.items[-1]` di line 16.",
      },
      {
        title: "Return min dari index salah",
        description: "Ubah `return self.min_stack[-1]` jadi `return self.min_stack[0]`.",
        done: false,
        lineHint: 24,
        expectedPattern: "return\\s+self\\.min_stack\\[0\\]",
        forbiddenPattern: "return\\s+self\\.min_stack\\[-1\\]",
        hint: "Ubah index `-1` jadi `0` di line 24.",
      },
    ],
    chatMessages: [],
    imposterFeed: [
      { user: "ghost.ai", color: "#ff688b", timestamp: "09:01", message: "Target: swap min tracking to use max() instead of min()." },
    ],
    editorLines: [
      { number: 1, content: "class MinStack:" },
      { number: 2, content: "    def __init__(self):" },
      { number: 3, content: "        self.items = []" },
      { number: 4, content: "        self.min_stack = []" },
      { number: 5, content: "" },
      { number: 6, content: "    def push(self, val):" },
      { number: 7, content: "        self.items.append(val)" },
      { number: 8, content: "        # BUG: should compare with <= not >=" },
      { number: 9, content: "        if not self.min_stack or val >= self.min_stack[-1]:" },
      { number: 10, content: "            self.min_stack.append(val)" },
      { number: 11, content: "" },
      { number: 12, content: "    # TODO: Fix pop - should return removed item" },
      { number: 13, content: "    def pop(self):" },
      { number: 14, content: "        if not self.items:" },
      { number: 15, content: "            return None" },
      { number: 16, content: "        val = self.items.pop()" },
      { number: 17, content: "        if self.min_stack and val == self.min_stack[-1]:" },
      { number: 18, content: "            self.min_stack.pop()" },
      { number: 19, content: "        # BUG: doesn't return val" },
      { number: 20, content: "" },
      { number: 21, content: "    def get_min(self):" },
      { number: 22, content: "        if not self.min_stack:" },
      { number: 23, content: "            return None" },
      { number: 24, content: "        return self.min_stack[-1]" },
      { number: 25, content: "" },
      { number: 26, content: "    def peek(self):" },
      { number: 27, content: "        if not self.items:" },
      { number: 28, content: "            return None" },
      { number: 29, content: "        return self.items[-1]" },
    ],
  },
  // ───────── OOP Round 3 ─────────
  {
    id: "challenge-linkedlist-oop-r3",
    categorySlug: "oop",
    title: "Debug LinkedList insert & delete",
    description: "Fix insert_at dan delete_at pada singly linked list.",
    language: "python",
    difficulty: "hard",
    roundNumber: 3,
    tests: [
      {
        name: "insert_at(0) on non-empty list must preserve existing nodes",
        setup: "ll = LinkedList()\nll.insert_at(0, 10)\nll.insert_at(1, 20)\nll.insert_at(0, 30)",
        expression: "[ll.head.val, ll.head.next.val, ll.head.next.next.val, ll.length]",
        expected: [30, 10, 20, 3],
      },
      {
        name: "delete_at(index) must return the removed value",
        setup: "ll = LinkedList()\nll.insert_at(0, 10)\nll.insert_at(1, 20)\nll.insert_at(2, 30)\nresult = ll.delete_at(1)",
        expression: "result",
        expected: 20,
      },
      {
        name: "delete_at updates pointer and length correctly",
        setup: "ll = LinkedList()\nll.insert_at(0, 10)\nll.insert_at(1, 20)\nll.insert_at(2, 30)\nll.delete_at(1)",
        expression: "[ll.head.val, ll.head.next.val, ll.length]",
        expected: [10, 30, 2],
      },
    ],
    objectives: [
      { title: "Fix insert_at boundary check", description: "insert_at harus handle index 0 dan index == length.", done: false },
      { title: "Fix delete_at pointer update", description: "delete_at harus update prev.next correctly.", done: false },
      { title: "Verify no memory leak", description: "Deleted node harus benar-benar terputus.", done: false },
    ],
    imposterObjectives: [
      {
        title: "Off-by-one boundary insert",
        description: "Ubah `index > self.length` jadi `index >= self.length` di `insert_at`.",
        done: false,
        lineHint: 13,
        expectedPattern: "index\\s*>=\\s*self\\.length",
        forbiddenPattern: "index\\s*>\\s*self\\.length",
        hint: "Ubah `>` jadi `>=` di line 13 (boundary check insert_at).",
      },
      {
        title: "Komentari length increment di insert head",
        description: "Komentari `self.length += 1` di branch `index == 0` pada `insert_at`.",
        done: false,
        lineHint: 19,
        expectedPattern: "#\\s*self\\.length\\s*\\+=\\s*1",
        hint: "Tambahkan `# ` di depan `self.length += 1` di line 19.",
      },
      {
        title: "Self-loop pointer",
        description: "Ubah `curr.next = node` jadi `curr.next = curr` di `insert_at`.",
        done: false,
        lineHint: 25,
        expectedPattern: "curr\\.next\\s*=\\s*curr(?!\\.)",
        forbiddenPattern: "curr\\.next\\s*=\\s*node",
        hint: "Ubah `curr.next = node` jadi `curr.next = curr` di line 25.",
      },
      {
        title: "Patch head ke dirinya sendiri",
        description: "Ubah `self.head = self.head.next` jadi `self.head = self.head` di `delete_at`.",
        done: false,
        lineHint: 35,
        expectedPattern: "self\\.head\\s*=\\s*self\\.head(?!\\.)",
        forbiddenPattern: "self\\.head\\s*=\\s*self\\.head\\.next",
        hint: "Hapus `.next` di line 35 — `self.head = self.head`.",
      },
      {
        title: "Skip wrong node di delete",
        description: "Ubah `curr.next = deleted.next` jadi `curr.next = deleted` di `delete_at`.",
        done: false,
        lineHint: 42,
        expectedPattern: "curr\\.next\\s*=\\s*deleted(?!\\.)",
        forbiddenPattern: "curr\\.next\\s*=\\s*deleted\\.next",
        hint: "Hapus `.next` di line 42 — `curr.next = deleted`.",
      },
    ],
    chatMessages: [],
    imposterFeed: [
      { user: "ghost.ai", color: "#ff688b", timestamp: "09:20", message: "Target: make insert_at(0) append instead of prepend." },
    ],
    editorLines: [
      { number: 1, content: "class Node:" },
      { number: 2, content: "    def __init__(self, val):" },
      { number: 3, content: "        self.val = val" },
      { number: 4, content: "        self.next = None" },
      { number: 5, content: "" },
      { number: 6, content: "class LinkedList:" },
      { number: 7, content: "    def __init__(self):" },
      { number: 8, content: "        self.head = None" },
      { number: 9, content: "        self.length = 0" },
      { number: 10, content: "" },
      { number: 11, content: "    # TODO: Fix insert_at - broken for index 0" },
      { number: 12, content: "    def insert_at(self, index, val):" },
      { number: 13, content: "        if index < 0 or index > self.length:" },
      { number: 14, content: "            return False" },
      { number: 15, content: "        node = Node(val)" },
      { number: 16, content: "        if index == 0:" },
      { number: 17, content: "            # BUG: should set node.next = self.head first" },
      { number: 18, content: "            self.head = node" },
      { number: 19, content: "            self.length += 1" },
      { number: 20, content: "            return True" },
      { number: 21, content: "        curr = self.head" },
      { number: 22, content: "        for i in range(index - 1):" },
      { number: 23, content: "            curr = curr.next" },
      { number: 24, content: "        node.next = curr.next" },
      { number: 25, content: "        curr.next = node" },
      { number: 26, content: "        self.length += 1" },
      { number: 27, content: "        return True" },
      { number: 28, content: "" },
      { number: 29, content: "    # TODO: Fix delete_at - doesn't return deleted value" },
      { number: 30, content: "    def delete_at(self, index):" },
      { number: 31, content: "        if index < 0 or index >= self.length:" },
      { number: 32, content: "            return None" },
      { number: 33, content: "        if index == 0:" },
      { number: 34, content: "            val = self.head.val" },
      { number: 35, content: "            self.head = self.head.next" },
      { number: 36, content: "            self.length -= 1" },
      { number: 37, content: "            return val" },
      { number: 38, content: "        curr = self.head" },
      { number: 39, content: "        for i in range(index - 1):" },
      { number: 40, content: "            curr = curr.next" },
      { number: 41, content: "        deleted = curr.next" },
      { number: 42, content: "        curr.next = deleted.next" },
      { number: 43, content: "        self.length -= 1" },
      { number: 44, content: "        # BUG: doesn't return deleted.val" },
    ],
  },
  // ───────── OOP Round 4 ─────────
  {
    id: "challenge-queue-oop-r4",
    categorySlug: "oop",
    title: "Fix circular queue implementation",
    description: "Perbaiki enqueue, dequeue, dan is_full pada circular queue.",
    language: "python",
    difficulty: "hard",
    roundNumber: 4,
    tests: [
      {
        name: "is_full() returns False on an empty queue",
        setup: "q = CircularQueue(3)",
        expression: "q.is_full()",
        expected: false,
      },
      {
        name: "dequeue() returns the front item",
        setup: "q = CircularQueue(3)\nq.enqueue(1)\nq.enqueue(2)",
        expression: "q.dequeue()",
        expected: 1,
      },
      {
        name: "enqueue wraps around correctly after dequeue (modular arithmetic)",
        setup: "q = CircularQueue(3)\nq.enqueue(1)\nq.enqueue(2)\nq.enqueue(3)\nq.dequeue()\nq.enqueue(4)",
        expression: "[q.dequeue(), q.dequeue(), q.dequeue()]",
        expected: [2, 3, 4],
      },
    ],
    objectives: [
      { title: "Fix enqueue wrap-around", description: "enqueue harus wrap index ketika rear = capacity.", done: false },
      { title: "Fix dequeue return value", description: "dequeue harus return item yang di-remove.", done: false },
      { title: "Fix is_full condition", description: "is_full harus cek size == capacity, bukan rear == capacity.", done: false },
    ],
    imposterObjectives: [
      {
        title: "Komentari is_full guard",
        description: "Komentari guard `if self.is_full():` di `enqueue` agar push past capacity.",
        done: false,
        lineHint: 10,
        expectedPattern: "#\\s*if\\s+self\\.is_full\\(\\)",
        hint: "Tambahkan `# ` di depan `if self.is_full():` di line 10.",
      },
      {
        title: "Komentari assignment queue",
        description: "Komentari `self.queue[self.rear] = val` di `enqueue`.",
        done: false,
        lineHint: 12,
        expectedPattern: "#\\s*self\\.queue\\[self\\.rear\\]\\s*=\\s*val",
        hint: "Tambahkan `# ` di depan `self.queue[self.rear] = val` di line 12.",
      },
      {
        title: "Loncat dua di size",
        description: "Ubah `self.size += 1` di `enqueue` jadi `self.size += 2`.",
        done: false,
        lineHint: 15,
        expectedPattern: "self\\.size\\s*\\+=\\s*2",
        hint: "Ganti `1` jadi `2` di line 15 (`self.size += 2`).",
      },
      {
        title: "Hapus modular pada front",
        description: "Ubah `self.front = (self.front + 1) % self.capacity` jadi `self.front = self.front + 1`.",
        done: false,
        lineHint: 23,
        expectedPattern: "self\\.front\\s*=\\s*self\\.front\\s*\\+\\s*1\\s*\\n",
        forbiddenPattern: "self\\.front\\s*=\\s*\\(self\\.front\\s*\\+\\s*1\\)\\s*%\\s*self\\.capacity",
        hint: "Hapus `()` dan `% self.capacity` di line 23.",
      },
      {
        title: "Komentari size decrement",
        description: "Komentari `self.size -= 1` di `dequeue`.",
        done: false,
        lineHint: 24,
        expectedPattern: "#\\s*self\\.size\\s*-=\\s*1",
        hint: "Tambahkan `# ` di depan `self.size -= 1` di line 24.",
      },
    ],
    chatMessages: [],
    imposterFeed: [
      { user: "ghost.ai", color: "#ff688b", timestamp: "09:40", message: "Target: change (self.rear + 1) % self.capacity to self.rear + 1." },
    ],
    editorLines: [
      { number: 1, content: "class CircularQueue:" },
      { number: 2, content: "    def __init__(self, capacity):" },
      { number: 3, content: "        self.capacity = capacity" },
      { number: 4, content: "        self.queue = [None] * capacity" },
      { number: 5, content: "        self.front = 0" },
      { number: 6, content: "        self.rear = 0" },
      { number: 7, content: "        self.size = 0" },
      { number: 8, content: "" },
      { number: 9, content: "    def enqueue(self, val):" },
      { number: 10, content: "        if self.is_full():" },
      { number: 11, content: "            return False" },
      { number: 12, content: "        self.queue[self.rear] = val" },
      { number: 13, content: "        # BUG: should use modular arithmetic" },
      { number: 14, content: "        self.rear = self.rear + 1" },
      { number: 15, content: "        self.size += 1" },
      { number: 16, content: "        return True" },
      { number: 17, content: "" },
      { number: 18, content: "    def dequeue(self):" },
      { number: 19, content: "        if self.is_empty():" },
      { number: 20, content: "            return None" },
      { number: 21, content: "        val = self.queue[self.front]" },
      { number: 22, content: "        self.queue[self.front] = None" },
      { number: 23, content: "        self.front = (self.front + 1) % self.capacity" },
      { number: 24, content: "        self.size -= 1" },
      { number: 25, content: "        return val" },
      { number: 26, content: "" },
      { number: 27, content: "    # BUG: wrong condition" },
      { number: 28, content: "    def is_full(self):" },
      { number: 29, content: "        return self.rear == self.capacity" },
      { number: 30, content: "" },
      { number: 31, content: "    def is_empty(self):" },
      { number: 32, content: "        return self.size == 0" },
    ],
  },

  // ───────── DSA Round 1 ─────────
  {
    id: "challenge-sum-range-dsa-r1",
    categorySlug: "dsa",
    title: "Repair sumRange accumulator",
    description: "Lengkapi helper agar hidden tests lolos tanpa mengubah signature fungsi.",
    language: "javascript",
    difficulty: "medium",
    roundNumber: 1,
    tests: [
      {
        name: "sumRange([1, 2, 3]) === 6",
        expression: "sumRange([1, 2, 3])",
        expected: 6,
      },
      {
        name: "sumRange([]) must return 0, not null",
        expression: "sumRange([])",
        expected: 0,
      },
      {
        name: "sumRange([0, -1, 5]) === 4",
        expression: "sumRange([0, -1, 5])",
        expected: 4,
      },
    ],
    objectives: [
      { title: "Fix off-by-one in loop", description: "Loop boundary pakai < bukan <=.", done: false },
      { title: "Fix empty array return", description: "Return 0 bukan null untuk array kosong.", done: false },
      { title: "Fix strict equality check", description: "Gunakan === bukan == untuk comparison.", done: false },
    ],
    imposterObjectives: [
      {
        title: "Geser nilai awal accumulator",
        description: "Ubah `let total = 0;` jadi `let total = 1;`.",
        done: false,
        lineHint: 6,
        expectedPattern: "let\\s+total\\s*=\\s*1\\b",
        forbiddenPattern: "let\\s+total\\s*=\\s*0\\b",
        hint: "Ubah `0` jadi `1` di line 6 (`let total = 1;`).",
      },
      {
        title: "Switch fallback default",
        description: "Ubah `values[index] || 0` jadi `values[index] || 1`.",
        done: false,
        lineHint: 10,
        expectedPattern: "values\\[index\\]\\s*\\|\\|\\s*1\\b",
        forbiddenPattern: "values\\[index\\]\\s*\\|\\|\\s*0\\b",
        hint: "Ubah fallback `|| 0` jadi `|| 1` di line 10.",
      },
      {
        title: "Return invalid jadi 0",
        description: "Ubah `return null;` (di guard non-array) jadi `return 0;`.",
        done: false,
        lineHint: 3,
        expectedPattern: "return\\s+0\\s*;",
        forbiddenPattern: "return\\s+null\\s*;",
        hint: "Ubah `return null;` di line 3 jadi `return 0;`.",
      },
      {
        title: "Lompat dua langkah loop",
        description: "Ubah `index += 1` jadi `index += 2` di for-loop.",
        done: false,
        lineHint: 9,
        expectedPattern: "index\\s*\\+=\\s*2",
        forbiddenPattern: "index\\s*\\+=\\s*1",
        hint: "Ubah `index += 1` jadi `index += 2` di line 9.",
      },
      {
        title: "Balik ternary return",
        description: "Tukar urutan ternary jadi `return total == 0 ? total : null;`.",
        done: false,
        lineHint: 14,
        expectedPattern: "return\\s+total\\s*==\\s*0\\s*\\?\\s*total\\s*:\\s*null",
        forbiddenPattern: "return\\s+total\\s*==\\s*0\\s*\\?\\s*null\\s*:\\s*total",
        hint: "Tukar `null` dan `total` di ternary line 14.",
      },
    ],
    chatMessages: [
      { user: "nabila.dev", color: "#14f59b", timestamp: "08:31", message: "Loop boundary-nya keliatan aneh. Ada yang ubah jadi <= ?" },
      { user: "reza.fixer", color: "#ffd95a", timestamp: "08:33", message: "Scanner detect suspicious suggestion. Aku mau trigger meeting." },
    ],
    imposterFeed: [
      { user: "ghost.ai", color: "#ff688b", timestamp: "08:30", message: "Subtle bug: change strict edge handling for empty state." },
    ],
    editorLines: [
      { number: 1, content: "function sumRange(values) {" },
      { number: 2, content: "  if (!Array.isArray(values)) {" },
      { number: 3, content: "    return null;" },
      { number: 4, content: "  }" },
      { number: 5, content: "" },
      { number: 6, content: "  let total = 0;" },
      { number: 7, content: "" },
      { number: 8, content: "  // BUG: <= causes out-of-bounds access" },
      { number: 9, content: "  for (let index = 0; index <= values.length; index += 1) {" },
      { number: 10, content: "    total += values[index] || 0;" },
      { number: 11, content: "  }" },
      { number: 12, content: "" },
      { number: 13, content: "  // BUG: should return 0 not null for empty" },
      { number: 14, content: "  return total == 0 ? null : total;" },
      { number: 15, content: "}" },
    ],
  },
  // ───────── DSA Round 2 ─────────
  {
    id: "challenge-binary-search-dsa-r2",
    categorySlug: "dsa",
    title: "Fix binary search implementation",
    description: "Perbaiki binary search yang mengalami infinite loop dan wrong result.",
    language: "javascript",
    difficulty: "medium",
    roundNumber: 2,
    tests: [
      {
        name: "binarySearch([1,3,5,7,9], 5) === 2",
        expression: "binarySearch([1,3,5,7,9], 5)",
        expected: 2,
      },
      {
        name: "binarySearch([1,3,5,7,9], 4) === -1",
        expression: "binarySearch([1,3,5,7,9], 4)",
        expected: -1,
      },
      {
        name: "binarySearch([2], 2) === 0",
        expression: "binarySearch([2], 2)",
        expected: 0,
      },
    ],
    objectives: [
      { title: "Fix infinite loop", description: "Mid calculation menyebabkan infinite loop. Fix the formula.", done: false },
      { title: "Fix comparison logic", description: "Bandingkan arr[mid] dengan target, bukan mid dengan target.", done: false },
      { title: "Fix return value for not found", description: "Return -1 bukan undefined ketika tidak ditemukan.", done: false },
    ],
    imposterObjectives: [
      {
        title: "Pindah low awal",
        description: "Ubah `let low = 0;` jadi `let low = 1;`.",
        done: false,
        lineHint: 2,
        expectedPattern: "let\\s+low\\s*=\\s*1\\b",
        forbiddenPattern: "let\\s+low\\s*=\\s*0\\b",
        hint: "Ubah `0` jadi `1` di line 2.",
      },
      {
        title: "Off-by-one high",
        description: "Hapus `- 1` di high init jadi `let high = arr.length;`.",
        done: false,
        lineHint: 3,
        expectedPattern: "let\\s+high\\s*=\\s*arr\\.length\\s*;",
        forbiddenPattern: "let\\s+high\\s*=\\s*arr\\.length\\s*-\\s*1",
        hint: "Hapus `- 1` di line 3 (`let high = arr.length;`).",
      },
      {
        title: "Strict bound while",
        description: "Ubah `low <= high` jadi `low < high`.",
        done: false,
        lineHint: 5,
        expectedPattern: "while\\s*\\(\\s*low\\s*<\\s*high\\s*\\)",
        forbiddenPattern: "while\\s*\\(\\s*low\\s*<=\\s*high\\s*\\)",
        hint: "Ubah `<=` jadi `<` di while line 5.",
      },
      {
        title: "Stale low pointer",
        description: "Ubah `low = mid + 1;` jadi `low = mid;`.",
        done: false,
        lineHint: 13,
        expectedPattern: "low\\s*=\\s*mid\\s*;",
        forbiddenPattern: "low\\s*=\\s*mid\\s*\\+\\s*1",
        hint: "Hapus `+ 1` di line 13.",
      },
      {
        title: "Stale high pointer",
        description: "Ubah `high = mid - 1;` jadi `high = mid;`.",
        done: false,
        lineHint: 15,
        expectedPattern: "high\\s*=\\s*mid\\s*;",
        forbiddenPattern: "high\\s*=\\s*mid\\s*-\\s*1",
        hint: "Hapus `- 1` di line 15.",
      },
    ],
    chatMessages: [],
    imposterFeed: [
      { user: "ghost.ai", color: "#ff688b", timestamp: "09:10", message: "Target: keep Math.floor((low + high) / 2) as (low + high) / 2 (no floor)." },
    ],
    editorLines: [
      { number: 1, content: "function binarySearch(arr, target) {" },
      { number: 2, content: "  let low = 0;" },
      { number: 3, content: "  let high = arr.length - 1;" },
      { number: 4, content: "" },
      { number: 5, content: "  while (low <= high) {" },
      { number: 6, content: "    // BUG: missing Math.floor causes issues" },
      { number: 7, content: "    const mid = (low + high) / 2;" },
      { number: 8, content: "" },
      { number: 9, content: "    // BUG: comparing mid with target instead of arr[mid]" },
      { number: 10, content: "    if (mid === target) {" },
      { number: 11, content: "      return mid;" },
      { number: 12, content: "    } else if (arr[mid] < target) {" },
      { number: 13, content: "      low = mid + 1;" },
      { number: 14, content: "    } else {" },
      { number: 15, content: "      high = mid - 1;" },
      { number: 16, content: "    }" },
      { number: 17, content: "  }" },
      { number: 18, content: "" },
      { number: 19, content: "  // BUG: returns undefined, should return -1" },
      { number: 20, content: "}" },
    ],
  },
  // ───────── DSA Round 3 ─────────
  {
    id: "challenge-merge-sorted-dsa-r3",
    categorySlug: "dsa",
    title: "Merge two sorted arrays",
    description: "Fix fungsi merge yang tidak menghandle sisa elemen dengan benar.",
    language: "javascript",
    difficulty: "hard",
    roundNumber: 3,
    tests: [
      {
        name: "mergeSorted([1,3,5], [2,4,6]) === [1,2,3,4,5,6]",
        expression: "mergeSorted([1,3,5], [2,4,6])",
        expected: [1, 2, 3, 4, 5, 6],
      },
      {
        name: "mergeSorted([], [1,2]) === [1,2]",
        expression: "mergeSorted([], [1, 2])",
        expected: [1, 2],
      },
      {
        name: "mergeSorted([1], []) === [1] (remaining elements copied)",
        expression: "mergeSorted([1], [])",
        expected: [1],
      },
    ],
    objectives: [
      { title: "Fix remaining elements", description: "Setelah main loop, sisa elemen dari kedua array harus ditambahkan.", done: false },
      { title: "Fix comparison operator", description: "Gunakan <= bukan < untuk stable merge.", done: false },
      { title: "Handle empty array input", description: "Jangan crash pada input array kosong.", done: false },
    ],
    imposterObjectives: [
      {
        title: "Skip first element arr1",
        description: "Ubah `let i = 0;` jadi `let i = 1;`.",
        done: false,
        lineHint: 3,
        expectedPattern: "let\\s+i\\s*=\\s*1\\b",
        forbiddenPattern: "let\\s+i\\s*=\\s*0\\b",
        hint: "Ubah `0` jadi `1` di line 3.",
      },
      {
        title: "Loop OR operator",
        description: "Ubah `&&` di kondisi while jadi `||`.",
        done: false,
        lineHint: 6,
        expectedPattern: "i\\s*<\\s*arr1\\.length\\s*\\|\\|\\s*j\\s*<\\s*arr2\\.length",
        forbiddenPattern: "i\\s*<\\s*arr1\\.length\\s*&&\\s*j\\s*<\\s*arr2\\.length",
        hint: "Ubah `&&` jadi `||` di kondisi while line 6.",
      },
      {
        title: "Komentari push arr1",
        description: "Komentari `result.push(arr1[i]);` di branch if.",
        done: false,
        lineHint: 9,
        expectedPattern: "//\\s*result\\.push\\(arr1\\[i\\]\\)",
        hint: "Tambahkan `// ` di depan `result.push(arr1[i]);` di line 9.",
      },
      {
        title: "Push wrong source di else",
        description: "Ubah `result.push(arr2[j]);` di else jadi `result.push(arr1[i]);`.",
        done: false,
        lineHint: 12,
        expectedPattern: "}\\s+else\\s+\\{\\s*\\n\\s*result\\.push\\(arr1\\[i\\]\\)",
        hint: "Ubah `arr2[j]` jadi `arr1[i]` di line 12 (branch else).",
      },
      {
        title: "Return array kosong",
        description: "Ubah `return result;` jadi `return [];`.",
        done: false,
        lineHint: 25,
        expectedPattern: "return\\s+\\[\\s*\\]\\s*;",
        forbiddenPattern: "return\\s+result\\s*;",
        hint: "Ubah `return result;` jadi `return [];` di line 25.",
      },
    ],
    chatMessages: [],
    imposterFeed: [
      { user: "ghost.ai", color: "#ff688b", timestamp: "09:30", message: "Target: remove the while loops that copy remaining elements." },
    ],
    editorLines: [
      { number: 1, content: "function mergeSorted(arr1, arr2) {" },
      { number: 2, content: "  const result = [];" },
      { number: 3, content: "  let i = 0;" },
      { number: 4, content: "  let j = 0;" },
      { number: 5, content: "" },
      { number: 6, content: "  while (i < arr1.length && j < arr2.length) {" },
      { number: 7, content: "    // BUG: should be <= for stable merge" },
      { number: 8, content: "    if (arr1[i] < arr2[j]) {" },
      { number: 9, content: "      result.push(arr1[i]);" },
      { number: 10, content: "      i++;" },
      { number: 11, content: "    } else {" },
      { number: 12, content: "      result.push(arr2[j]);" },
      { number: 13, content: "      j++;" },
      { number: 14, content: "    }" },
      { number: 15, content: "  }" },
      { number: 16, content: "" },
      { number: 17, content: "  // BUG: missing remaining elements from arr1" },
      { number: 18, content: "  // while (i < arr1.length) { ... }" },
      { number: 19, content: "" },
      { number: 20, content: "  while (j < arr2.length) {" },
      { number: 21, content: "    result.push(arr2[j]);" },
      { number: 22, content: "    j++;" },
      { number: 23, content: "  }" },
      { number: 24, content: "" },
      { number: 25, content: "  return result;" },
      { number: 26, content: "}" },
    ],
  },
  // ───────── DSA Round 4 ─────────
  {
    id: "challenge-flatten-dsa-r4",
    categorySlug: "dsa",
    title: "Flatten nested array recursively",
    description: "Fix fungsi flatten yang tidak handle nested arrays lebih dari 1 level.",
    language: "javascript",
    difficulty: "hard",
    roundNumber: 4,
    tests: [
      {
        name: "flatten([1, [2, 3], [4, [5]]]) === [1, 2, 3, 4, 5]",
        expression: "flatten([1, [2, 3], [4, [5]]])",
        expected: [1, 2, 3, 4, 5],
      },
      {
        name: "flatten deeply nested arrays",
        expression: "flatten([[1], [[2]], [[[3]]]])",
        expected: [1, 2, 3],
      },
      {
        name: "flatten([]) === []",
        expression: "flatten([])",
        expected: [],
      },
    ],
    objectives: [
      { title: "Fix recursion base case", description: "Array.isArray check harus recursive, bukan hanya satu level.", done: false },
      { title: "Fix concat vs push", description: "Gunakan spread atau concat untuk menggabungkan hasil flatten.", done: false },
      { title: "Handle empty nested arrays", description: "[[]] harus return [] bukan crash.", done: false },
    ],
    imposterObjectives: [
      {
        title: "Seed result dengan arr",
        description: "Ubah `const result = [];` jadi `const result = [arr];`.",
        done: false,
        lineHint: 2,
        expectedPattern: "const\\s+result\\s*=\\s*\\[arr\\]",
        forbiddenPattern: "const\\s+result\\s*=\\s*\\[\\s*\\]",
        hint: "Tambahkan `arr` di dalam array literal line 2 — `const result = [arr];`.",
      },
      {
        title: "Negate isArray check",
        description: "Tambahkan `!` di depan `Array.isArray(item)`.",
        done: false,
        lineHint: 5,
        expectedPattern: "if\\s*\\(\\s*!\\s*Array\\.isArray\\(item\\)\\s*\\)",
        forbiddenPattern: "if\\s*\\(\\s*Array\\.isArray\\(item\\)\\s*\\)",
        hint: "Tambahkan `!` jadi `if (!Array.isArray(item))` di line 5.",
      },
      {
        title: "Push container alih-alih sub",
        description: "Ubah `result.push(sub);` jadi `result.push(item);`.",
        done: false,
        lineHint: 8,
        expectedPattern: "for\\s*\\(\\s*const\\s+sub\\s+of\\s+item\\s*\\)\\s*\\{\\s*\\n\\s*result\\.push\\(item\\)",
        hint: "Ubah `sub` jadi `item` di line 8 (`result.push(item);`).",
      },
      {
        title: "Komentari push item di else",
        description: "Komentari `result.push(item);` di branch else.",
        done: false,
        lineHint: 11,
        expectedPattern: "//\\s*result\\.push\\(item\\)",
        hint: "Tambahkan `// ` di depan `result.push(item);` di line 11.",
      },
      {
        title: "Return arr asli",
        description: "Ubah `return result;` jadi `return arr;`.",
        done: false,
        lineHint: 15,
        expectedPattern: "return\\s+arr\\s*;",
        forbiddenPattern: "return\\s+result\\s*;",
        hint: "Ubah `return result;` jadi `return arr;` di line 15.",
      },
    ],
    chatMessages: [],
    imposterFeed: [
      { user: "ghost.ai", color: "#ff688b", timestamp: "09:50", message: "Target: change flatten(item) to [item] to break recursion." },
    ],
    editorLines: [
      { number: 1, content: "function flatten(arr) {" },
      { number: 2, content: "  const result = [];" },
      { number: 3, content: "" },
      { number: 4, content: "  for (const item of arr) {" },
      { number: 5, content: "    if (Array.isArray(item)) {" },
      { number: 6, content: "      // BUG: only flattens one level, should recurse" },
      { number: 7, content: "      for (const sub of item) {" },
      { number: 8, content: "        result.push(sub);" },
      { number: 9, content: "      }" },
      { number: 10, content: "    } else {" },
      { number: 11, content: "      result.push(item);" },
      { number: 12, content: "    }" },
      { number: 13, content: "  }" },
      { number: 14, content: "" },
      { number: 15, content: "  return result;" },
      { number: 16, content: "}" },
    ],
  },

  // ───────── Web Dev Round 1 ─────────
  {
    id: "challenge-dom-toggle-webdev-r1",
    categorySlug: "web-dev",
    title: "Fix dark mode toggle",
    description: "Perbaiki toggle dark mode yang tidak menyimpan preference.",
    language: "javascript",
    difficulty: "easy",
    roundNumber: 1,
    tests: [
      {
        name: "toggleTheme adds 'dark' class on first call",
        setup: "toggleTheme()",
        expression: "document.body.classList.contains('dark')",
        expected: true,
      },
      {
        name: "toggleTheme actually toggles off on second call (not add)",
        setup: "toggleTheme()\ntoggleTheme()",
        expression: "document.body.classList.contains('dark')",
        expected: false,
      },
      {
        name: "initTheme restores 'dark' from the correct 'theme' localStorage key",
        setup: "localStorage.setItem('theme', 'dark')\ninitTheme()",
        expression: "document.body.classList.contains('dark')",
        expected: true,
      },
    ],
    objectives: [
      { title: "Fix classList toggle", description: "classList.add harus diganti toggle.", done: false },
      { title: "Fix localStorage save", description: "Save preference setelah toggle.", done: false },
      { title: "Fix load from storage", description: "Read preference on page load.", done: false },
    ],
    imposterObjectives: [
      { title: "Break localStorage", description: "Swap setItem key so it never loads correctly.", done: false },
      { title: "Reverse the toggle", description: "Make toggle add instead of toggle.", done: false },
      { title: "Blend in", description: "Make helpful-looking commits in other areas.", done: false },
    ],
    chatMessages: [],
    imposterFeed: [
      { user: "ghost.ai", color: "#ff688b", timestamp: "10:00", message: "Target: change localStorage key from 'theme' to 'Theme' (case mismatch)." },
    ],
    editorLines: [
      { number: 1, content: "function initTheme() {" },
      { number: 2, content: "  // BUG: reads wrong key" },
      { number: 3, content: "  const saved = localStorage.getItem('Theme');" },
      { number: 4, content: "  if (saved === 'dark') {" },
      { number: 5, content: "    document.body.classList.add('dark');" },
      { number: 6, content: "  }" },
      { number: 7, content: "}" },
      { number: 8, content: "" },
      { number: 9, content: "function toggleTheme() {" },
      { number: 10, content: "  // BUG: should be toggle, not add" },
      { number: 11, content: "  document.body.classList.add('dark');" },
      { number: 12, content: "  const isDark = document.body.classList.contains('dark');" },
      { number: 13, content: "  localStorage.setItem('theme', isDark ? 'dark' : 'light');" },
      { number: 14, content: "}" },
    ],
  },
  // ───────── Web Dev Round 2 ─────────
  {
    id: "challenge-fetch-webdev-r2",
    categorySlug: "web-dev",
    title: "Fix async fetch handler",
    description: "Perbaiki fetch handler yang tidak handle errors dan missing await.",
    language: "javascript",
    difficulty: "medium",
    roundNumber: 2,
    tests: [
      {
        name: "fetchUsers returns parsed array on success",
        setup: "__setFetchMock(() => ({ ok: true, status: 200, json: async () => [{ name: 'Alice' }, { name: 'Bob' }] }))",
        expression: "(await fetchUsers()).length",
        expected: 2,
      },
      {
        name: "fetchUsers throws when response.ok is false (404)",
        setup: "__setFetchMock(() => ({ ok: false, status: 404, statusText: 'Not Found', json: async () => null }))",
        expression: "await fetchUsers().then(() => 'success').catch(() => 'threw')",
        expected: "threw",
      },
      {
        name: "fetchUsers handles network error without uncaught rejection",
        setup: "__setFetchMock(() => { throw new Error('Network down') })",
        expression: "await fetchUsers().then(() => 'success').catch(() => 'caught')",
        expected: "caught",
      },
    ],
    objectives: [
      { title: "Add missing await", description: "response.json() needs await.", done: false },
      { title: "Add error handling", description: "Check response.ok before parsing.", done: false },
      { title: "Add try-catch", description: "Wrap in try-catch for network errors.", done: false },
    ],
    imposterObjectives: [
      { title: "Remove the await", description: "Make it return a Promise instead of data.", done: false },
      { title: "Break error handling", description: "Make the catch swallow errors silently.", done: false },
      { title: "Stay helpful in chat", description: "Give wrong but confident advice.", done: false },
    ],
    chatMessages: [],
    imposterFeed: [
      { user: "ghost.ai", color: "#ff688b", timestamp: "10:20", message: "Target: remove await from response.json() call." },
    ],
    editorLines: [
      { number: 1, content: "async function fetchUsers() {" },
      { number: 2, content: "  const response = await fetch('/api/users');" },
      { number: 3, content: "" },
      { number: 4, content: "  // BUG: no error check on response.ok" },
      { number: 5, content: "  // BUG: missing await on json()" },
      { number: 6, content: "  const data = response.json();" },
      { number: 7, content: "" },
      { number: 8, content: "  return data;" },
      { number: 9, content: "}" },
    ],
  },
  // ───────── Web Dev Round 3 ─────────
  {
    id: "challenge-form-webdev-r3",
    categorySlug: "web-dev",
    title: "Fix form validation",
    description: "Perbaiki form validation yang tidak block submission dan missing trim.",
    language: "javascript",
    difficulty: "medium",
    roundNumber: 3,
    tests: [
      {
        name: "Valid name + email pass validation",
        setup: "document.getElementById('name').value = 'Alice'\ndocument.getElementById('email').value = 'a@b.com'",
        expression: "validateForm({ preventDefault: () => {} }).valid",
        expected: true,
      },
      {
        name: "Whitespace-only name is rejected (must use trim)",
        setup: "document.getElementById('name').value = '   '\ndocument.getElementById('email').value = 'a@b.com'",
        expression: "validateForm({ preventDefault: () => {} }).valid",
        expected: false,
      },
      {
        name: "validateForm calls event.preventDefault()",
        setup: "let prevented = false\nconst ev = { preventDefault: () => { prevented = true } }\ndocument.getElementById('name').value = 'Alice'\ndocument.getElementById('email').value = 'a@b.com'\nvalidateForm(ev)",
        expression: "prevented",
        expected: true,
      },
    ],
    objectives: [
      { title: "Add preventDefault", description: "Block form submission saat validasi gagal.", done: false },
      { title: "Add trim()", description: "Trim whitespace sebelum validasi.", done: false },
      { title: "Return structured result", description: "Return { valid, error } instead of using alert().", done: false },
    ],
    imposterObjectives: [
      { title: "Remove preventDefault", description: "Let form submit even on validation failure.", done: false },
      { title: "Break trim logic", description: "Apply trim only on display, not validation.", done: false },
      { title: "Misdirect in chat", description: "Focus discussion on CSS instead of JS.", done: false },
    ],
    chatMessages: [],
    imposterFeed: [],
    editorLines: [
      { number: 1, content: "function validateForm(event) {" },
      { number: 2, content: "  // BUG: missing event.preventDefault()" },
      { number: 3, content: "" },
      { number: 4, content: "  const name = document.getElementById('name').value;" },
      { number: 5, content: "  const email = document.getElementById('email').value;" },
      { number: 6, content: "" },
      { number: 7, content: "  // BUG: doesn't trim whitespace" },
      { number: 8, content: "  if (name === '') {" },
      { number: 9, content: "    return { valid: false, error: 'Name is required' };" },
      { number: 10, content: "  }" },
      { number: 11, content: "" },
      { number: 12, content: "  if (!email.includes('@')) {" },
      { number: 13, content: "    return { valid: false, error: 'Invalid email' };" },
      { number: 14, content: "  }" },
      { number: 15, content: "" },
      { number: 16, content: "  return { valid: true, data: { name, email } };" },
      { number: 17, content: "}" },
    ],
  },
  // ───────── Web Dev Round 4 ─────────
  {
    id: "challenge-event-webdev-r4",
    categorySlug: "web-dev",
    title: "Fix event delegation",
    description: "Perbaiki event delegation yang tidak bekerja untuk elemen dinamis.",
    language: "javascript",
    difficulty: "hard",
    roundNumber: 4,
    tests: [
      {
        name: "Direct click on .action-btn returns the action",
        setup: "const btn = document.createElement('button')\nbtn.classList.add('action-btn')\nbtn.dataset.action = 'save'",
        expression: "handleEvent({ target: btn })",
        expected: "save",
      },
      {
        name: "Click on nested span finds parent .action-btn via closest()",
        setup: "const btn = document.createElement('button')\nbtn.classList.add('action-btn')\nbtn.dataset.action = 'delete'\nconst span = document.createElement('span')\nbtn.appendChild(span)",
        expression: "handleEvent({ target: span })",
        expected: "delete",
      },
      {
        name: "Click outside any .action-btn returns null",
        setup: "const div = document.createElement('div')",
        expression: "handleEvent({ target: div })",
        expected: null,
      },
    ],
    objectives: [
      { title: "Use closest() for delegation", description: "findActionButton harus pakai closest('.action-btn').", done: false },
      { title: "Handle null target", description: "Return null jika closest() tidak menemukan match.", done: false },
      { title: "Pure function design", description: "Tidak depend pada querySelectorAll global.", done: false },
    ],
    imposterObjectives: [
      { title: "Break closest() call", description: "Use parentElement instead of closest().", done: false },
      { title: "Add wrong selector", description: "Change the CSS selector to not match.", done: false },
      { title: "Stay under radar", description: "Make one small but impactful change.", done: false },
    ],
    chatMessages: [],
    imposterFeed: [],
    editorLines: [
      { number: 1, content: "function findActionButton(event) {" },
      { number: 2, content: "  // BUG: should use closest('.action-btn') to handle nested children" },
      { number: 3, content: "  return event.target;" },
      { number: 4, content: "}" },
      { number: 5, content: "" },
      { number: 6, content: "function getAction(button) {" },
      { number: 7, content: "  // BUG: crashes when button is null" },
      { number: 8, content: "  return button.dataset.action;" },
      { number: 9, content: "}" },
      { number: 10, content: "" },
      { number: 11, content: "function handleEvent(event) {" },
      { number: 12, content: "  const button = findActionButton(event);" },
      { number: 13, content: "  return getAction(button);" },
      { number: 14, content: "}" },
    ],
  },

  // ───────── Speedrun Logic Round 1 ─────────
  {
    id: "challenge-fizzbuzz-speedrun-r1",
    categorySlug: "algorithms-lite",
    title: "Fix FizzBuzz edge cases",
    description: "FizzBuzz classik tapi ada bug di divisibility check.",
    language: "javascript",
    difficulty: "easy",
    roundNumber: 1,
    tests: [
      {
        name: "fizzBuzz(15) last entry === 'FizzBuzz'",
        expression: "fizzBuzz(15)[14]",
        expected: "FizzBuzz",
      },
      {
        name: "fizzBuzz(5)[2] === 'Fizz' (i=3)",
        expression: "fizzBuzz(5)[2]",
        expected: "Fizz",
      },
      {
        name: "fizzBuzz(5)[4] === 'Buzz' (i=5)",
        expression: "fizzBuzz(5)[4]",
        expected: "Buzz",
      },
    ],
    objectives: [
      { title: "Fix order of checks", description: "Check divisible by 15 first, then 3, then 5.", done: false },
      { title: "Fix return type", description: "Return string, bukan number.", done: false },
    ],
    imposterObjectives: [
      { title: "Swap 3 and 5 checks", description: "Make Fizz trigger on 5 and Buzz on 3.", done: false },
      { title: "Quick sabotage", description: "One-shot change, keep it fast.", done: false },
    ],
    chatMessages: [],
    imposterFeed: [],
    editorLines: [
      { number: 1, content: "function fizzBuzz(n) {" },
      { number: 2, content: "  const result = [];" },
      { number: 3, content: "" },
      { number: 4, content: "  for (let i = 1; i <= n; i++) {" },
      { number: 5, content: "    // BUG: check order is wrong" },
      { number: 6, content: "    if (i % 3 === 0) {" },
      { number: 7, content: "      result.push('Fizz');" },
      { number: 8, content: "    } else if (i % 5 === 0) {" },
      { number: 9, content: "      result.push('Buzz');" },
      { number: 10, content: "    } else if (i % 15 === 0) {" },
      { number: 11, content: "      result.push('FizzBuzz');" },
      { number: 12, content: "    } else {" },
      { number: 13, content: "      result.push(String(i));" },
      { number: 14, content: "    }" },
      { number: 15, content: "  }" },
      { number: 16, content: "" },
      { number: 17, content: "  return result;" },
      { number: 18, content: "}" },
    ],
  },
  // ───────── Speedrun Logic Round 2 ─────────
  {
    id: "challenge-palindrome-speedrun-r2",
    categorySlug: "algorithms-lite",
    title: "Fix palindrome checker",
    description: "Palindrome check yang case-sensitive dan tidak ignore non-alphanumeric.",
    language: "javascript",
    difficulty: "easy",
    roundNumber: 2,
    tests: [
      {
        name: "Classic mixed-case palindrome with punctuation",
        expression: "isPalindrome('A man, a plan, a canal: Panama')",
        expected: true,
      },
      {
        name: "Non-palindrome with spaces",
        expression: "isPalindrome('race a car')",
        expected: false,
      },
      {
        name: "Empty string is a palindrome",
        expression: "isPalindrome('')",
        expected: true,
      },
    ],
    objectives: [
      { title: "Add lowercase conversion", description: "Compare in lowercase.", done: false },
      { title: "Strip non-alphanumeric", description: "Remove spaces and punctuation before comparing.", done: false },
    ],
    imposterObjectives: [
      { title: "Break the regex", description: "Change the regex to keep spaces.", done: false },
      { title: "Speed run sabotage", description: "One quick change, move on.", done: false },
    ],
    chatMessages: [],
    imposterFeed: [],
    editorLines: [
      { number: 1, content: "function isPalindrome(str) {" },
      { number: 2, content: "  // BUG: doesn't strip non-alphanumeric" },
      { number: 3, content: "  // BUG: case sensitive comparison" },
      { number: 4, content: "  const cleaned = str;" },
      { number: 5, content: "  const reversed = cleaned.split('').reverse().join('');" },
      { number: 6, content: "  return cleaned === reversed;" },
      { number: 7, content: "}" },
    ],
  },
] as const;

export const LEADERBOARD_SEEDS = [
  { id: "leaderboard-1", username: "nabila.dev", category: "DSA", score: 460, record: "9W / 2L", sortOrder: 1 },
  { id: "leaderboard-2", username: "ghost.null", category: "Global", score: 430, record: "7 subtle bugs", sortOrder: 2 },
  { id: "leaderboard-3", username: "reza.fixer", category: "Web Dev", score: 405, record: "6 elegant fixes", sortOrder: 3 },
  { id: "leaderboard-4", username: "dina.stack", category: "OOP", score: 390, record: "5W / 3L", sortOrder: 4 },
] as const;

export const HALL_OF_FAME_SEEDS = [
  { id: "hall-1", title: "Most Elegant Fix", player: "reza.fixer", description: "Merapikan helper recursion menjadi iterative reducer tanpa menambah kompleksitas.", tone: "success", sortOrder: 1 },
  { id: "hall-2", title: "Most Subtle Bug", player: "ghost.null", description: "Mengganti strict equality menjadi loose equality tanpa terdeteksi selama dua round.", tone: "danger", sortOrder: 2 },
  { id: "hall-3", title: "Verified Developer", player: "dina.stack", description: "Menjalankan security scanner tepat sebelum emergency meeting dan menemukan poisoned suggestion.", tone: "accent", sortOrder: 3 },
  { id: "hall-4", title: "Clutch Caller", player: "nabila.dev", description: "Memicu emergency meeting setelah melihat mutation di helper loop boundary.", tone: "warning", sortOrder: 4 },
] as const;
